### ISSUE TITLE
NO MAGIC NUMBERS

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#2]
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L22
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L24
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L26
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L42

You should know better already right now :) Don't use magic numbers, define constants and use it in your code where needed and in all of the outputs too!

**Comment by asharif123** [comment]
fixed issue #2 by getting rid of magic numbers

**Comment by incredibleLeitman** [comment]
This is not solved yet 👆 

There are still magic numbers in the Console.WriteLine calls!

However, having a constant for 0 is not really necessary if this does not have a very special meaning other than zero

**Comment by mayisa87** [comment]
Instead of hardcode write 1 or 100 in your output, you should output the value of your constants

Just as an example, you do it exactly the same as outputing values of a variable:
Console.WriteLine($"\nYour guess is too low! You have {GuessesLeft} guesses left!");

Why: If you output hardcoded 1 or 100 for example, and you change your constant value for maximum to 200. What if you forget to change the hardcoded value in your output?

**Comment by asharif123** [comment]
fixed issue #2 by getting rid of magic numbers in console.writeline statement
